# Generated by Django 5.2.17 on 2026-09-11 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('serial_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=128)),
                ('capacity', models.IntegerField()),
                ('configuration', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('part_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(editable=False, max_length=160, primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('status', models.CharField(choices=[('Arrived', 'Arrived'), ('Pending', 'Pending'), ('Requested', 'Requested')], default='Requested', max_length=32)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.aircraft')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.material')),
            ],
            options={
                'ordering': ['arrival_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('aircraft', 'material', 'arrival_date'), name='unique_order_aircraft_material_date')],
            },
        ),
    ]
