# Generated by Django 5.2.17 on 2026-09-11 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('import', 'Import'), ('clear', 'Clear')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=32)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('total_created', models.IntegerField(default=0)),
                ('total_updated', models.IntegerField(default=0)),
                ('total_deleted', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
